#! /bin/bash

curl -i localhost:8000
curl -i -H 'x-okta-verification-challenge: The challenge' localhost:8000
curl -i -H "Content-Type: application/json" -d '{"event":"UserLogin"}' localhost:8000
credentials=$(echo -n admin:$OKTA_HOOK_PASSWORD | base64)
curl -i -H "Authorization: Basic $credentials" -H "Content-Type: application/json" -d '{"event":"UserLogin"}' localhost:8000

